spring:
  datasource:
    url: jdbc:sqlserver://localhost:1433;databaseName=backend;encrypt=false;columnEncryptionSetting=Enabled;keyStoreAuthentication=JavaKeyStorePassword;keyStoreLocation="C:\Program Files\Java\jdk-17.0.4\bin\keystore.pfx";keyStoreSecret=P@ssw0rd;
    driverClassName: com.microsoft.sqlserver.jdbc.SQLServerDriver
    username: sa
    password: P@ssw0rd
  jpa:
    hibernate:
      dialect: org.hibernate.dialect.SQLServer2012Dialect
      ddl-auto: update
    show-sql: 'true'

